public enum ScriptState {
    WALKING,
    INTERACTING_RENU,
    SELECTING_DESTINATION,
    WALKING_TO_ENTRANCE,
    ENTERING_CAM_TORUM,
    WAITING_INSIDE,
    WALKING_TO_BANK,
    BANKING,
    IDLE
}
